#!/usr/bin/env python3

import os
import mwclient
import argparse
import mwparserfromhell
import subprocess


def link_is_pdf(tag):
    return tag.text is not None and 'pdf' in tag.text


class Edition:
    def __init__(self):
        self.score_info = None
        self.editor_params = None
        self.cpdlno_params = None
        self.pdfs = []

    def add_pdf(self, pdf_link):
        self.pdfs.append(pdf_link.title)

    def info(self):
        if self.score_info:
            return '{{PreviewScoreInfo|%s}}' % self.score_info
        return ''

    def editor(self):
        if self.editor_params:
            return '{{PreviewEditor|%s}}' % self.editor_params
        return ''

    def cpdlno(self):
        if self.cpdlno_params:
            return 'CPDL #' + self.cpdlno_params
        return ''

    def __repr__(self):
        return 'Edition({}, {})'.format(self.info(), self.pdfs)


def strparams(tag):
    return '|'.join(str(p) for p in tag.params)


def process_text(text):
    parsed = mwparserfromhell.parse(text)
    titles = {}
    editions = []

    for tag in parsed.filter():
        if isinstance(tag, mwparserfromhell.nodes.heading.Heading):
            titles[tag.level] = tag.title
        elif isinstance(tag, mwparserfromhell.nodes.wikilink.Wikilink):
            if link_is_pdf(tag) and titles.get(2) == 'Music files':
                editions[-1].add_pdf(tag)
        elif isinstance(tag, mwparserfromhell.nodes.template.Template):
            if tag.name == 'CPDLno':
                editions.append(Edition())
                editions[-1].cpdlno_params = strparams(tag)
            elif tag.name == 'Editor':
                editions[-1].editor_params = strparams(tag)
            elif tag.name == 'ScoreInfo':
                editions[-1].score_info = strparams(tag)

    return editions


def fetch_pdf(cpdl, link, workdir):
    if link.startswith('Media:'):
        filename = link.partition(':')[2]
        pdf = cpdl.images[filename]
        imageinfo = pdf.imageinfo
        sha1 = imageinfo['sha1']
        localname = workdir + '/' + sha1
        if not os.path.exists(localname):
            with open(localname + '.pdf', 'wb') as localfile:
                pdf.download(localfile)
        return sha1, imageinfo
    else:
        raise 1


def convert(workdir, filehash):
    def fn(extn):
        return workdir + '/' + filehash + '.' + extn

    subprocess.check_call(
            'pdftoppm -singlefile -scale-to-x 1000 -scale-to-y -1 -png'.split() +
            [fn('pdf'), fn('uncut')])
    subprocess.check_call(
            ['convert', fn('uncut.png'), '-crop', '1000x500+0+0', '+repage', fn('png')])


def upload(cpdl, wd, filehash, orig):
    print('Uploading', filehash, 'for source PDF', orig)
    with open(wd + '/' + filehash + '.png', 'rb') as src:
        cpdl.upload(
                file=src, filename='Preview' + filehash + '.png',
                description='Automatic preview of {}, generated by PreviewBot.'.format(orig))


def inject_gallery(text, gallery_entries):
    lines = text.split('\n')
    for i, line in enumerate(lines):
        if line.strip() == '==General Information==':
            break
    lines[i:i] = ['==Score previews==',
                  '<div style="clear: both"></div>'
                  '<gallery widths=500 heights=250>'
                  ] + gallery_entries + ['</gallery>']
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--saved-page')
    parser.add_argument('--page')
    parser.add_argument('--assume-uploaded', action='store_true')
    parser.add_argument('--just-print-gallery', action='store_true')
    args = parser.parse_args()

    username, pwd = open(os.path.expanduser('~/.config/cpdl')).read().split()

    cpdl = mwclient.Site(('http', 'cpdl.org'), path='/wiki/')
    cpdl.login(username, pwd)

    page = cpdl.pages[args.page]
    if args.saved_page:
        with open(args.saved_page) as sp:
            text = sp.read()
    else:
        text = page.text()

    editions = process_text(text)

    gallery_entries = []
    for e in editions:
        for p in e.pdfs:
            filehash, imageinfo = fetch_pdf(cpdl, p, 'wd')
            if not args.assume_uploaded:
                convert('wd', filehash)
                upload(cpdl, 'wd', filehash, p)
            gallery_entries.append('File:{preview}|{info}|link={url}'.format(
                preview='Preview' + filehash + '.png',
                info='{}; {}; {}'.format(e.info(), e.cpdlno(), e.editor()),
                url=("{{filepath:%s}}" % p.rpartition(':')[2])))

    if args.just_print_gallery:
        print('Gallery text:\n' + '\n'.join(gallery_entries))
    else:
        text = inject_gallery(text, gallery_entries)
        page.save(text, 'Generate PDF previews.')


if __name__ == '__main__':
    main()
